In [2]:
import numpy as np

In [3]:
#В общем виде вектор столбец можно задать следующим образом:.
v = np.array([[1],[2]])
print(v)

[[1]
 [2]]


In [4]:
#В Numpy можно создать квадратную матрицу с помощью метода array():
m_sqr_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m_sqr_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# В Numpy есть еще одни способ создания матриц - это построение объекта типа
# matrix с помощью одноименного метода. Задать матрицу можно в виде списка:
m_sqr_mx = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m_sqr_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
# Также доступен стиль Matlab, когда между элементами ставятся пробелы, а строки
# разделяются точкой с запятой, при этом такое описание должно быть передано в
# виде строки:
m_sqr_mx = np.matrix('1 2 3; 4 5 6; 7 8 9')
print(m_sqr_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


______________________
Диагональная матрица

In [7]:
# Диагональная матрица
#Диагональную матрицу можно построить вручную, задав только значения элементам на главной диагонали:
m_diag = [[1, 0, 0], [0, 5, 0], [0, 0, 9]]
m_diag = np.matrix(m_diag)
print(m_diag)

[[1 0 0]
 [0 5 0]
 [0 0 9]]


In [8]:
m_sqr_mx = np.matrix('1 2 3; 4 5 6; 7 8 9')

In [9]:
# Извлечем ее главную диагональ:
diag = np.diag(m_sqr_mx)
print(diag)

[1 5 9]


In [10]:
m_diag_np = np.diag(np.diag(m_sqr_mx))
print(m_diag_np)

[[1 0 0]
 [0 5 0]
 [0 0 9]]


__________________
Единичная матрица

In [11]:
# Создадим единичную матрицу на базе списка, который передадим в качестве
# аргумента функции matrix():
m_e = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
m_e_np = np.matrix(m_e)
print(m_e_np)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [13]:
#Такой способ не очень удобен, к счастью для нас, для построения такого типа
#матриц в библиотеке Numpy есть специальная функция — eye():
m_eye = np.eye(3)
print(m_eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


_______________
Нулевая матрица

In [14]:
m_zeros = np.zeros((3, 3))
print(m_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


_______________________
Задание матрицы в общем виде

In [15]:
# Если у вас уже есть данные о содержимом матрицы, то создать ее можно, используя
# списки Python или функцию matrix() из библиотеки Numpy:
m_mx = np.matrix('1 2 3; 4 5 6')
print(m_mx)

[[1 2 3]
 [4 5 6]]


In [16]:
# Если же вы хотите создать матрицу заданного размера
# с произвольным
# содержимым, чтобы потом ее заполнить, проще всего для того использовать
# функцию zeros(), которая создаст матрицу заданного размера, заполненную нулями:

m_var = np.zeros((2,5))
print(m_var)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


______________________
Транспонирование матрицы

In [ ]:
# Транспонирование матрицы - это процесс замены строк матрицы на ее столбцы, а
# столбцов, соответственно, на строки. Полученная в результате матрица называется
# транспонированной. Символ операции транспонирования - буква T


In [17]:
A = np.matrix('1 2 3; 4 5 6')
print(A)

[[1 2 3]
 [4 5 6]]


In [18]:
# Транспонируем матрицу с помощью метода transpose():
A_t = A.transpose()
print(A_t)

[[1 4]
 [2 5]
 [3 6]]


In [19]:
# Существует сокращенный вариант получения транспонированной матрицы, он
# удобен для практического использования:
print(A.T)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# Свойство 1. Дважды транспонированная матрица равна исходной матрице:


In [20]:
A = np.matrix('1 2 3; 4 5 6')
print(A)
R = (A.T).T
print(R)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [ ]:
# Свойство 2. Транспонированная сумма матриц равна сумме транспонированных матриц:

In [21]:
A = np.matrix('1 2 3; 4 5 6')
B = np.matrix('7 8 9; 0 7 5')
L = (A + B).T
R = A.T + B.T
print(L)
print(R)

[[ 8  4]
 [10 12]
 [12 11]]
[[ 8  4]
 [10 12]
 [12 11]]


In [22]:
# Свойство 3. Транспонированное произведение матриц равно произведению
# транспонированных матриц, расставленных в обратном порядке:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
L = (A.dot(B)).T
R = (B.T).dot(A.T)
print(L)
print(R)

[[19 43]
 [22 50]]
[[19 43]
 [22 50]]


In [23]:
# Свойство 4. Транспонированное произведение матрицы на число равно произведению этого числа на транспонированную матрицу:
A = np.matrix('1 2 3; 4 5 6')
k = 3
L = (k * A).T
R = k * (A.T)
print(L)
print(R)

[[ 3 12]
 [ 6 15]
 [ 9 18]]
[[ 3 12]
 [ 6 15]
 [ 9 18]]


In [25]:
# Свойство 5. Определители исходной и транспонированной матрицы совпадают:
A = np.matrix('1 2; 3 4')
A_det = np.linalg.det(A)
A_T_det = np.linalg.det(A.T)
print(format(A_det, '.9g'))
print(format(A_T_det, '.9g'))

-2
-2


_________________
Действия над матрицами
_________________
Умножение на число

In [26]:
A = np.matrix('1 2 3; 4 5 6')
C = 3 * A
print(C)

[[ 3  6  9]
 [12 15 18]]


In [27]:
# Свойство 1. Произведение единицы и любой заданной матрицы равно заданной матрице: 
A = np.matrix('1 2; 3 4')
L = 1 * A
R = A
print(L)
print(R)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [28]:
# Свойство 2. Произведение нуля и любой матрицы равно нулевой матрице,
# размерность которой равна исходной матрицы:
A = np.matrix('1 2; 3 4')
Z = np.matrix('0 0; 0 0')
L = 0 * A
R = Z
print(L)
print(R)

[[0 0]
 [0 0]]
[[0 0]
 [0 0]]


In [29]:
# Свойство 3. Произведение матрицы на сумму чисел равно сумме произведений
# матрицы на каждое из этих чисел:
A = np.matrix('1 2; 3 4')
p = 2
q = 3
L = (p + q) * A
R = p * A + q * A
print(L)
print(R)

[[ 5 10]
 [15 20]]
[[ 5 10]
 [15 20]]


In [31]:
# Свойство 4. Произведение матрицы на произведение двух чисел равно произведению второго числа и заданной матрицы, умноженному на первое число:
A = np.matrix('1 2; 3 4')
p = 2 
q = 3
L = (p * q) * A
R = p * (q * A)
print(L)
print(R)

[[ 6 12]
 [18 24]]
[[ 6 12]
 [18 24]]


In [34]:
# Свойство 5. Произведение суммы матриц на число равно сумме произведений этих
# матриц на заданное число:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
k = 3
L = k * (A + B)
R = k * A + k * B
print(L)
print(R)

[[18 24]
 [30 36]]
[[18 24]
 [30 36]]


________________________
Сложение

In [35]:
# Складывать можно только матрицы одинаковой размерности — то есть матрицы, у
# которых совпадает количество столбцов и строк.
A = np.matrix('1 6 3; 8 2 7')
B = np.matrix('8 1 5; 6 9 12')
C = A + B
print(C)

[[ 9  7  8]
 [14 11 19]]


In [36]:
# Свойство 1. Коммутативность сложения. От перестановки матриц их сумма не изменяется:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
L = A + B
R = B + A
print(L)
print(R)

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [37]:
# Свойство 2. Ассоциативность сложения. Результат сложения трех и более матриц
# не зависит от порядка, в котором эта операция будет выполняться:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
C = np.matrix('1 7; 9 3')
L = A + (B + C)
R = (A + B) + C
print(L)
print(R)

[[ 7 15]
 [19 15]]
[[ 7 15]
 [19 15]]


In [38]:
# Свойство 3. Для любой матрицы A существует противоположная ей (-A) такая, что их сумма является нулевой матрицей Z
A = np.matrix('1 2; 3 4')
Z = np.matrix('0 0; 0 0')
L = A + (-1)*A
print(L)
print(Z)

[[0 0]
 [0 0]]
[[0 0]
 [0 0]]


_________________________
Умножение матриц

In [39]:
# Умножение матриц это уже более сложная операция,по сравнению с
# рассмотренными выше. Умножать можно только матрицы, отвечающие следующему
# требованию: количество столбцов первой матрицы должно быть равно числу
# строк второй матрицы.
# Решим задачу умножения матриц на языке Python. Для этого будем использовать
# функцию dot() из библиотеки Numpy:
A = np.matrix('1 2 3; 4 5 6')
B = np.matrix('7 8; 9 1; 2 3')
C = A.dot(B)
print(C)

[[31 19]
 [85 55]]


In [41]:
# Свойство 1. Ассоциативность умножения. Результат умножения матриц не зависит
# от порядка, в котором будет выполняться эта операция:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
C = np.matrix('2 4; 7 8')
L = A.dot(B.dot(C))
R = (A.dot(B)).dot(C)
print(L)
print(R)

[[192 252]
 [436 572]]
[[192 252]
 [436 572]]


In [42]:
# Свойство 2. Дистрибутивность умножения. Произведение матрицы на сумму
# матриц равно сумме произведений матриц:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
C = np.matrix('2 4; 7 8')
L = A.dot(B + C)
R = A.dot(B) + A.dot(C)
print(L)
print(R)

[[35 42]
 [77 94]]
[[35 42]
 [77 94]]


In [45]:
# Свойство 3. Умножение матриц в общем виде не коммутативно. Это означает, что
# для матриц не выполняется правило независимости произведения от перестановки множителей:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
L = A.dot(B)
R = B.dot(A)
print(L)
print(L)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [46]:
# Свойство 4. Произведение заданной матрицы на единичную равно исходной матрице:
A = np.matrix('1 2; 3 4')
E = np.matrix('1 0; 0 1')
L = E.dot(A)
R = A.dot(E)
print(L)
print(R)
print(A)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [47]:
# Свойство 5. Произведение заданной матрицы на нулевую матрицу равно нулевой матрице:
A = np.matrix('1 2; 3 4')
Z = np.matrix('0 0; 0 0') 
L = Z.dot(A)
R = A.dot(Z)
print(L)
print(R)
print(Z)

[[0 0]
 [0 0]]
[[0 0]
 [0 0]]
[[0 0]
 [0 0]]


______________________
Определитель матрицы

In [3]:
# Определитель матрицы размера n x n( -го порядка) является одной из ее численных характеристик. Определитель матрицы A
# обозначается как |A| или det(A) его также называют детерминантом.

# Минор элемента определителя - это определитель, полученный из данного, путем вычеркивания всех элементов строки и
# столбца, на пересечении которых стоит данный элемент.

# Введем еще одно понятие - алгебраическое дополнение элемента определителя - это минор этого элемента, взятый со знаком плюс или минус:
# В общем виде вычислить определитель матрицы можно через разложение
# определителя по элементам строки или столбца. Суть в том, что определитель равен
# сумме произведений элементов любой строки или столбца на их алгебраические
# дополнения.

# На Python определитель посчитать очень просто. Создадим матрицу размера 3x3 из приведенного выше численного примера:

A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]


In [4]:
# Для вычисления определителя этой матрицы воспользуемся функцией det() из пакета linalg.
np.linalg.det(A)

-14.000000000000009

In [5]:
# Свойство 1. Определитель матрицы остается неизменным при ее транспонировании:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)
print(A.T)
det_A = round(np.linalg.det(A), 3)
det_A_t = round(np.linalg.det(A.T), 3)
print(det_A)
print(det_A_t)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]
[[-4 10  8]
 [-1  4  3]
 [ 2 -1  1]]
-14.0
-14.0


In [6]:
# Свойство 2. Если у матрицы есть строка или столбец, состоящие из нулей, то определитель такой матрицы равен нулю:
A = np.matrix('-4 -1 2; 0 0 0; 8 3 1')
print(A)
np.linalg.det(A)

[[-4 -1  2]
 [ 0  0  0]
 [ 8  3  1]]


0.0

In [14]:
# Свойство 3. При перестановке строк матрицы знак ее определителя меняется на противоположный:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)
B = np.matrix('10 4 -1; -4 -1 2; 8 3 1')
print(B)
round(np.linalg.det(A), 3)
round(np.linalg.det(B), 3)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]
[[10  4 -1]
 [-4 -1  2]
 [ 8  3  1]]


14.0

In [23]:
round(np.linalg.det(B), 3)

-14.0

In [15]:
# Свойство 4. Если у матрицы есть две одинаковые строки, то ее определитель равен нулю:
A = np.matrix('-4 -1 2; -4 -1 2; 8 3 1')
print(A)
np.linalg.det(A)

[[-4 -1  2]
 [-4 -1  2]
 [ 8  3  1]]


0.0

In [16]:
# Свойство 5. Если все элементы строки или столбца матрицы умножить на какое-то число, то и определитель будет умножен на это число:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)
k = 2
B = A.copy()
B[2, :] = k * B[2, :]
print(B)
det_A = round(np.linalg.det(A), 3)
det_B = round(np.linalg.det(B), 3)
det_A * k
det_B

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]
[[-4 -1  2]
 [10  4 -1]
 [16  6  2]]


-28.0

In [21]:
# Свойство 6. Если все элементы строки или столбца можно представить как сумму 
# двух слагаемых, то определитель такой матрицы равен сумме определителей двух
# соответствующих матриц:
A = np.matrix('-4 -1 2; -4 -1 2; 8 3 1')
B = np.matrix('-4 -1 2; 8 3 2; 8 3 1')
C = A.copy()
C[1, :] += B[1, :]
print(C)
print(A)
print(B)
round(np.linalg.det(C), 3)
round(np.linalg.det(A), 3) + round(np.linalg.det(B), 3)

[[-4 -1  2]
 [ 4  2  4]
 [ 8  3  1]]
[[-4 -1  2]
 [-4 -1  2]
 [ 8  3  1]]
[[-4 -1  2]
 [ 8  3  2]
 [ 8  3  1]]


4.0

In [22]:
# Свойство 7. Если к элементам одной строки прибавить элементы другой строки
# умноженные на одно и тоже число, то определитель матрицы не изменится:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
k = 2
B = A.copy()
B[1, :] = B[1, :] + k * B[0, :]
print(A)
print(B)
round(np.linalg.det(A), 3)
round(np.linalg.det(B), 3)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]
[[-4 -1  2]
 [ 2  2  3]
 [ 8  3  1]]


-14.0

In [27]:
# Свойство 8. Если строка или столбец матрицы является линейной комбинацией
# других строк (столбцов), то определитель такой матрицы равен нулю:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)
k = 2
A[1, :] = A[0, :] + k * A[2, :]
round(np.linalg.det(A), 3)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]


0.0

In [28]:
# Свойство 9. Если матрица содержит пропорциональные строки, то ее определитель равен нулю:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)
k = 2
A[1, :] = k * A[0, :]
print(A)
round(np.linalg.det(A), 3)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]
[[-4 -1  2]
 [-8 -2  4]
 [ 8  3  1]]


0.0

_________________________
Обратная матрица

In [30]:
# Введем понятие союзной матрицы. Союзная матрица A* строится на базе
# исходной A путем замены всех элементов матрицы A на их алгебраические
# дополнения.

# Решим задачу определения обратной матрицы на Python. Для получения обратной
# матрицы будем использовать функцию inv():
A = np.matrix('1 -3; 2 5')
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.45454545  0.27272727]
 [-0.18181818  0.09090909]]


In [31]:
# Свойство 1. Обратная матрица обратной матрицы есть исходная матрица:
A = np.matrix('1. -3.; 2. 5.')
A_inv = np.linalg.inv(A)
A_inv_inv = np.linalg.inv(A_inv)
print(A)
print(A_inv_inv)

[[ 1. -3.]
 [ 2.  5.]]
[[ 1. -3.]
 [ 2.  5.]]


In [32]:
# Свойство 2. Обратная матрица транспонированной матрицы равна
# транспонированной матрице от обратной матрицы:
A = np.matrix('1. -3; 2. 5.')
L = np.linalg.inv(A.T)
R = (np.linalg.inv(A)).T
print(L)
print(R)

[[ 0.45454545 -0.18181818]
 [ 0.27272727  0.09090909]]
[[ 0.45454545 -0.18181818]
 [ 0.27272727  0.09090909]]


In [33]:
# Свойство 3. Обратная матрица произведения матриц равна произведению обратных матриц:
A = np.matrix('1. -3.; 2. 5.')
B = np.matrix('7. 6.; 1. 8.')
L = np.linalg.inv(A.dot(B))
R = np.linalg.inv(B).dot(np.linalg.inv(A))
print(L)
print(R)

[[ 0.09454545  0.03272727]
 [-0.03454545  0.00727273]]
[[ 0.09454545  0.03272727]
 [-0.03454545  0.00727273]]


________________________________
Ранг матрицы

In [ ]:
# Ранг матрицы является еще одной важной численной характеристикой. Рангом называют максимальное число линейно независимых строк (столбцов) матрицы.
# Линейная независимость означает, что строки (столбцы) не могут быть линейно выражены через другие строки (столбцы). Ранг матрицы можно найти через ее
# миноры, он равен наибольшему порядку минора, который не равен нулю. Существование ранга у матрицы не зависит от того квадратная она или нет.

In [34]:
# Вычислим ранг матрицы с помощью Python. Создадим единичную матрицу:
m_eye = np.eye(4)
print(m_eye)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [35]:
# Ранг такой матрицы равен количеству ее столбцов (или строк), в нашем случае ранг
# будет равен четырем, для его вычисления на Python воспользуемся функцией matrix_rank():
rank = np.linalg.matrix_rank(m_eye)
print(rank)

4


In [36]:
# Если мы приравняем элемент в нижнем правом углу к нулю, то ранг станет равен трем:
m_eye[3][3] = 0 
print(m_eye)
rank = np.linalg.matrix_rank(m_eye)
print(rank)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]
3


_______________________________
_______________________________
Решение систем линейных уравнений

________________________
Решение неоднородной системы в матричной форме

In [38]:
A = np.matrix('3 -1 2; 1 4 -1; 2 3 1')
B = np.matrix('-4; 10; 8')
print(A)
print(B)
A_inv = np.linalg.inv(A)
print(A_inv)
X = A_inv.dot(B)
print(X)

[[ 3 -1  2]
 [ 1  4 -1]
 [ 2  3  1]]
[[-4]
 [10]
 [ 8]]
[[ 0.5         0.5        -0.5       ]
 [-0.21428571 -0.07142857  0.35714286]
 [-0.35714286 -0.78571429  0.92857143]]
[[-1.]
 [ 3.]
 [ 1.]]


_______________________________
Метод Крамера

In [39]:
# Метод Крамера можно использовать для решения неоднородных систем линейных
# уравнений, при этом определитель главной матрицы системы должен быть
# отличен от нуля. Полученное данным методом решение будет единственным.
A = np.matrix('3 -1 2; 1 4 -1; 2 3 1')
print(A)
B = np.matrix('-4; 10; 8')
print(B)
A_det = np.linalg.det(A)
print(A_det)
X_m = np.matrix(A)
X_m[:, 0] = B
print(X_m)
Y_m = np.matrix(A)
Y_m[:, 1] = B
print(Y_m)
Z_m = np.matrix(A)
Z_m[:, 2] = B
print(Z_m)
x = np.linalg.det(X_m) / A_det
y = np.linalg.det(Y_m) / A_det
z = np.linalg.det(Z_m) / A_det
print(x)
print(y)
print(z)

[[ 3 -1  2]
 [ 1  4 -1]
 [ 2  3  1]]
[[-4]
 [10]
 [ 8]]
13.999999999999996
[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]
[[ 3 -4  2]
 [ 1 10 -1]
 [ 2  8  1]]
[[ 3 -1 -4]
 [ 1  4 10]
 [ 2  3  8]]
-1.0000000000000009
3.0000000000000013
0.9999999999999997


___________________________________
Метод Гаусса

_________________________________
Решение системы линейных уравнений на Python

In [40]:
A = np.matrix('3 -1 2; 1 4 -1; 2 3 1')
B = np.matrix('-4; 10; 8')
print(A)
print(B)
X = np.linalg.solve(A, B)
print(X)

[[ 3 -1  2]
 [ 1  4 -1]
 [ 2  3  1]]
[[-4]
 [10]
 [ 8]]
[[-1.]
 [ 3.]
 [ 1.]]


_______________________________
Глава 3. Основы векторной алгебры
_________________________________

Векторные и скалярные величины

In [ ]:
# В рамках геометрической интерпретации под вектором понимается
# направленный отрезок прямой, характеризуемый длиной и направлением.
# Если вектор рассматривать как алгебраический объект, то он может
# быть представлен в виде строки или столбца чисел, то есть в виде матрицы размера
# (1, n) либо (n, 1)2. Связь между геометрическим и алгебраическим представлением
# более подробно раскрыта в разделе 3.3 “Координаты вектора”.

# В физике и технических дисциплинах (механика, электротехника и т.п.) различают
# скалярные и векторные величины. Скалярной называется величина, которая
# характеризуется только числовым значением. Векторной называется
# величина, которая характеризуется числовым значением и направлением

# Вектор будем обозначать одной маленькой латинской буквой полужирного
# начертания, вот так: a , либо двумя большими латинскими буквами, первая
# обозначает точку начала, вторая - конц вектора: AB.

# Длина вектора (эту величину еще называют модуль вектора) изображается так |a|

In [41]:
# 1.Проекция вектора на ось
# Проекция вектора на ось равна произведению модуля вектора на косинус угла между вектором и осью.

# 2.Координаты вектора
# Координатами вектора называют его проекции на оси координат
A = np.array([1,2,3])
print(A)
B = np.array([3,5,2])
print(B)
AB = B - A
print(AB)

[1 2 3]
[3 5 2]
[ 2  3 -1]


_________________________
Модуль вектора и его направление в пространстве

In [43]:
# Модулем вектора называется величина, равная квадратному корню из суммы квадратов его координат:
# Направление вектора определяется косинусами углов между вектором и осями
# координат:
# α - угол между вектором и осью .
# β - угол между вектором и осью .
# γ - угол между вектором и осью .

AB = np.array([6,7,2])
module_AB = np.linalg.norm(AB)
print(module_AB)

# функции для вычисления косинусов:
cos_x = lambda a: a[0] / np.linalg.norm(a)
cos_y = lambda a: a[1] / np.linalg.norm(a)
cos_z = lambda a: a[2] / np.linalg.norm(a)
cos_x(AB)

9.433981132056603


0.6359987280038161

In [44]:
cos_y(AB)

0.741998516004452

In [45]:
cos_z(AB)

0.211999576001272

In [46]:
# Для того, чтобы получить значения косинусов в виде списка составим следующую функцию:
vect_cos = lambda a: [a[i] / np.linalg.norm(a) for i in range(len(a))]
vect_cos(AB)

[0.6359987280038161, 0.741998516004452, 0.211999576001272]

________________________________
Операции над векторами

Сложение векторов

In [47]:
# Геометрическое представление векторов прекрасно подходит для иллюстрации правила параллелограмма для сложения векторов
# Суть в том, что от конца первого вектора откладывается второй, а от конца второго -
# первый, в полученном на этих векторах параллелограмме проводится диагональ,
# которая и будет является результирующим вектором. Это правило можно упростить:
# достаточно отложить от конца первого вектора второй и соединить начало первого и
# конец второго, такой подход называется правилом треугольника
a = np.array([2,1])
b = np.array([1,3])
c = a + b
print(c)

[3 4]


______________
Вычитание векторов

In [48]:
a = np.array([2,1])
b = np.array([1,3])
c = b - a
print(c)

[-1  2]


________________________
Умножение вектора на число

In [49]:
a = np.array([2, 1])
k = 2
c = k * a
print(c)

[4 2]


_________________________
Скалярное произведение двух векторов

In [51]:
# Скалярным произведением двух векторов a и b называется число, равное
# произведению модулей этих векторов на косинус угла между ними:

# Если транспонировать один из векторов, то скалярное произведение можно
# выразить через операцию умножения матриц:
a = np.array([2, 7, 3])
b = np.array([5, 9, 3])
ab_scal = a.dot(b.T)
ab_scal

82

_________________________
Векторное произведение двух векторов

In [52]:
# Векторным произведение двух векторов и называется третий вектор , который удовлетворяет следующим условиям:
# 1. Вектор c перпендикулярен векторам a и b
# 2. Модуль вектора c определяется по формуле: |c| = |a * b|=|a|*|b|*sin(&)
# 3. Вектора a,b и c образуют правую тройку векторов.
a = np.array([2, 7, 3])
b = np.array([5, 9, 3])
# Найдем косинус угла между векторами. Это можно сделать двумя способами: - предварительно реализовав соответствующую формулу: 
vect_cos = lambda a, b: a.T.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))
# - воспользоваться уже готовой формулой из scipy, которая вычисляет косинусное расстояние:
# vect_cos(a, b)
vect_sin = lambda a, b: (1 - vect_cos(a, b)**2)**0.5
vect_sin(a, b)
prod_vect = lambda a, b: np.linalg.norm(a)*np.linalg.norm(b)*vect_sin(a, b)
prod_vect(a, b)

20.149441679609886

________________________
Смешанное произведение трех векторов

In [53]:
# Смешанное произведение трех векторов (его еще называют векторно-скалярным)
# определяется так: два вектора умножаются векторно, после этого, полученное
# произведение необходимо умножить на третий вектор скалярно.
a = [2, 7, 3]
b = [5, 9, 3]
c = [7, 4, 5]
vmp = np.matrix([a, b, c])
np.linalg.det(vmp)

-90.99999999999997

______________
Глава 4. Линейные векторные пространства
_______________
Общие сведения

In [ ]:
# Введем понятие линейного пространства. Рассмотрим такое множество X, на
# котором определена операция сложения элементов из этого множества и умножение
# элемента множества X на некоторое число. Здесь и далее под числом будем
# понимать число из множества действительных чисел R. При этом элемент,
# полученный в результате указанного выше сложения или умножения на число, также
# принадлежит множеству X.

# Если множество X обладает ниже перечисленными свойствами (их называют
# аксиомами линейного пространства), то такое множество называется линейным
# пространством. Если элементами такого линейного пространства являются
# векторы, то такое пространство называется линейным векторным пространством.
# В рамках данной главы под вектором будем понимать строку или столбце чисел.

In [2]:
# Свойство 1. Сложение элементов линейного пространства коммутативно. От перестановки слагаемых сумма не изменяется:
a = np.array([1,2]).T
b = np.array([3,4]).T
L = a + b
R = b + a
print(L)
print(R)

[4 6]
[4 6]


In [3]:
# Свойство 2. Сложение элементов линейного пространства ассоциативно. Результат
# суммирования ряда элементов не зависит от порядка суммирования:
a = np.array([[1,2]]).T
b = np.array([[3,4]]).T
c = np.array([[5,6]]).T
L = a +(b + c)
R = (a + b)+ c
print(L)
print(R)

[[ 9]
 [12]]
[[ 9]
 [12]]


In [4]:
# Свойство 3. Множество X содержит нулевой элемент, для которого справедливо следующее:
a = np.array([[1,2]]).T
z = np.array([[0,0]]).T
L = a + z
R = a
print(L)
print(R)

[[1]
 [2]]
[[1]
 [2]]


In [ ]:
# Свойство 4. В множестве X для любого элемента существует обратный ему
# элемент: если a - это элемент множества X , то (-a) - является обратным элементом
# для a, и он также содержится в множестве X.


In [6]:
a = np.array([[1,2]]).T
m_a = np.array([[-1,-2]]).T
z = np.array([[0,0]]).T
L = a + m_a
R = z
print(L)
print(R)

[[0]
 [0]]
[[0]
 [0]]


In [7]:
# Свойство 5. Произведение суммы элементов из множества X на число равно сумме
# произведений этого числа на данные элементы:
a = np.array([[1, 2]]).T
b = np.array([[3, 4]]).T
k = 2
L = k * (a + b)
R = k * a + k * b
print(L)
print(R)

[[ 8]
 [12]]
[[ 8]
 [12]]


In [9]:
# Свойство 6. Произведение суммы чисел на элемент множества X равно сумме
# произведений элемента на заданные числа:
a = np.array([[1,2]]).T
p = 2
q = 3 
L = (p+q)*a
R = p*a+q*a
print(L)
print(R)

[[ 5]
 [10]]
[[ 5]
 [10]]


In [11]:
# Свойство 7. Произведение чисел, умноженное на элемент из множества , равно
# произведению одного из чисел и элемента, умноженного на другое число:
a = np.array([[1,2]]).T
p = 2
q = 3
L = (p*q)*a
R = p*(q*a)
print(L)
print(R)

[[ 6]
 [12]]
[[ 6]
 [12]]


In [12]:
# Свойство 8. Множество X содержит единичный элемент, для которого справедливо следующее равенство:
a = np.array([[1, 2]]).T
k = 1
L = k*a
R = a
print(L)
print(R)

[[1]
 [2]]
[[1]
 [2]]


______________________
Линейная зависимость векторов

In [14]:
# Рассмотрим очень важную тему, которая имеет огромное практическое значение -
# линейная зависимость векторов. Пусть у нас есть система векторов x1,x2,...xn,
# как вы помните, каждый вектор представляет собой строку или столбец чисел xi = (xi1,xi2,...,xin).
# Составим следующее равенство: a1 x1 + a2 x2+...an xn = 0
# Если такое равенство выполняется при a1,a2...,an, не все из которых равны нулю,
# то такая система векторов x1,x2,...,xn называется линейно зависимой. Вектор
# z , который может быть представлен как сумма произведений векторов на числа,
# называется линейной комбинацией векторов: z = a1 x1 + a2 x2 + ... + an xn
# Для того, чтобы определить является ли заданная система векторов линейно
# зависимой, необходимо разложить вектора на компоненты и составить
# соответствующую систему уравнений, если она имеет ненулевое решение, то такая
# система векторов линейно зависима.

A = np.matrix('1 -1 2; 1 3 2; -2 1 -4')
np.linalg.det(A)

0.0

In [15]:
np.linalg.matrix_rank(A)

2

________________________
Базис системы векторов

In [ ]:
# У системы векторов можно выделить максимальную линейно независимую
# подсистему, которая характеризуется тем, что если в нее добавить еще один вектор
# (из данной системы), то она станет линейно зависимой.
# При этом, добавление к любой из данных подсистем вектора из заданной системы
# приведет к тому, что полученная система будет линейно зависимой.

# Для заданной конечной линейной системы векторов базисом называется любая ее
# максимальная линейно независимая подсистема, а число векторов в базисе
# называется рангом системы векторов. Если вы, по заданным векторам, построите
# матрицу, то ее ранг будет равен рангу базиса исходной системы векторов. Базис
# конечной линейной системы - это такой набор векторов, через который может быть
# выражен любой вектор системы. Другими словами, любой вектор из линейной
# системы является линейной комбинацией векторов базиса.

# Для линейного пространства векторов, так же как и для системы, существует понятие
# базиса. Базис линейного пространства - это упорядоченная независимая система
# векторов, через которую может быть выражен любой вектор этого пространства.
# Количество векторов в базисе называется размерностью пространства. Число
# pазличных базисов линейного пространства бесконечно. Когда мы говорим, что
# пространство трехмерно - это значит, что его базис состоит из трех векторов, и
# любая точка (вектор) пространства может быть определена через вектора базиса.

# Как было отмечено ранее, количество базисов линейного пространства бесконечно,
# это значит, что помимо естественного базиса существуют еще и другие. Все базисы
# линейного пространства связаны между собой. Мы можем переходить от одного
# базиса к другому при необходимости. Разберем этот вопрос более подробно.

______________________
Линейные операторы

In [16]:
# Для более интуитивного понимания данной темы, операторы, или как их еще
# называют отображения, можно воспринимать как функции особого вида. Оператор
# ставит в соответствие вектору x из линейного пространства X некоторый вектор y из
# линейного пространства Y. 
f = lambda x: np.dot(np.array([[1, 2], [0, 1]]), x.T)
x = np.array([1, 2])
x_ = f(x)
print(x_)

[5 2]


_____________________
Отражение вектора в себя

In [17]:
x = np.array([2,1])
A = np.array([[1,0],[0,1]])
print(A)

[[1 0]
 [0 1]]


In [18]:
# Создадим функцию f, которая будет реализовывать линейное отражение. Эту функцию будем использовать в следующих примерах:
f = lambda A, x: np.dot(A, x.T)
# Выполним линейное преобразование:
f(A, x)

array([2, 1])

_____________________
Масштабирование

In [24]:
x = np.array([2, 1])
A_m1 = np.array([[2, 0], [0, 2]])
f(A_m1, x)

array([4, 2])

In [25]:
A_m2 = np.array([[0.5, 0], [0, 3]])
f(A_m2, x)

array([1., 3.])

____________________
Отражение

In [26]:
# Отражение относительно той или иной оси является востребованной операцией в
# прикладных задачах. Рассмотрим горизонтальное (относительно оси ординат) и
# вертикальное (относительно оси абсцисс) отражение.



Горизонтальное отражение

In [27]:
z = np.array([2, 1])
A_hor = np.array([[-1, 0], [0, 1]])
f(A_hor, z)

array([-2,  1])

Вертикальное отражение

In [28]:
z = np.array([2, 1])
A_vert = np.array([[1, 0], [0, -1]])
f(A_vert, z)

array([ 2, -1])

__________________
Поворот

In [29]:
# Матрицы операторов, выполняющих поворот на заданный угол, имеют более
# интересное наполнение. Рассмотрим два линейных оператора: первый будет
# осуществлять поворот по часовой стрелке, второй - против.

По часовой стрелке

In [30]:
import math
z = np.array([2, 1])
A_rot_cl = np.array([[math.cos(math.pi/4), math.sin(math.pi/4)],[(-1)*math.sin(math.pi/4), math.cos(math.pi/4)]])
f(A_rot_cl, z)

array([ 2.12132034, -0.70710678])

Против часовой стрелке

In [31]:
import math
z = np.array([2, 1])
A_rot_not_cl = np.array([[math.cos(math.pi/3), (-1)*math.sin(math.pi/3)],[math.sin(math.pi/3), math.cos(math.pi/3)]])
f(A_rot_not_cl, z)

array([0.1339746 , 2.23205081])

_________________
Перемещение по осям

In [32]:
z = np.array([2,1,1]).T
A_mov = np.array([[1, 0, 1], [0, 1, 2], [0, 0, 1]])
f(A_mov, z)

array([3, 3, 1])

___
Эквивалентные преобразования применительно к СЛАУ

In [33]:
# В разделе 2.3 мы разбирали метод Гаусса для решения систем линейных
# алгебраических уравнений. Наша цель состояла приведении исходной системы
# уравнений к треугольному виду. Суть этой работы заключалась в том, что с
# исходной системой мы последовательно производили ряд преобразований, при этом
# система до и после этих преобразований имела одно и тоже решение. Такие
# преобразования называются эквивалентными.

# Различают три вида эквивалентных преобразований:
# 1. Перестановка двух уравнений в системе.
# 2. Умножение одного из уравнений системы на число, не равное нулю.
# 3. Прибавление одного уравнения к другому, умноженному на число.
# Применение эквивалентных преобразований удобно производить в матричном виде.

# 1. Перестановка двух уравнений в системе.
# Данному преобразованию соответствует перестановка строк в расширенной матрице
# системы. Для того, чтобы произвести перестановку строк достаточно заданную
# матрицу размера (m, n) умножить на единичную матрицу размера (n, n), в которой
# будут переставлены соответствующие строки.


# 2. Умножение одного из уравнений системы на число, не равное нулю.
# Для выполнения такого преобразования необходимо расширенную матрицу системы
# умножить слева на матрицу, которая используется для масштабирования вектора по
# заданному направлению:

# 3. Прибавление одного уравнения к другому, умноженному на число.
# Такое эквивалентное преобразование производится путем умножения
# соответствующей расширенной матрицы системы на матрицу следующего вида:

A = np.array([[3, -1, 2, -4], [1, 4, -1, 10], [2, 3, 1, 8]])
print(A)
# Теперь построим матрицы для выполнения эквивалентных преобразований:
R1 = np.array([[0, 0, 1], [0, 1, 0], [1, 0, 0]])
print(R1)
R2 = np.array([[1, 0, 0], [0.5, -1, 0], [1.5, 0, -1]])
print(R2)
R3 = np.array([[1, 0, 0], [0, 1, 0], [0, -2.2, -1]])
print(R3)
# Выполним необходимые матричные умножения:
R3.dot(R2.dot(R1.dot(A)))

[[ 3 -1  2 -4]
 [ 1  4 -1 10]
 [ 2  3  1  8]]
[[0 0 1]
 [0 1 0]
 [1 0 0]]
[[ 1.   0.   0. ]
 [ 0.5 -1.   0. ]
 [ 1.5  0.  -1. ]]
[[ 1.   0.   0. ]
 [ 0.   1.   0. ]
 [ 0.  -2.2 -1. ]]


array([[ 2. ,  3. ,  1. ,  8. ],
       [ 0. , -2.5,  1.5, -6. ],
       [ 0. ,  0. , -2.8, -2.8]])

In [38]:
# Если данный вопрос перевести на язык линейных операторов, то можно сделать
# следующее интересное наблюдение: задав умножение на соответствующую матрицу
# как линейное отображение, готовый результат мы можем получить через композицию
# линейных операторов — то есть последовательное их применение к результату
# полученному на предыдущем этапе. Рассмотрим это на примере. Создадим три
# линейных оператора:
def f1(x):
    R1 = np.array([[0, 0, 1], [0, 1, 0], [1, 0, 0]])
    return R1.dot(x)
def f2(x):
    R2 = np.array([[1, 0, 0], [0.5, -1, 0], [1.5, 0, -1]])
    return R2.dot(x)
def f3(x):
    R3 = np.array([[1, 0, 0], [0, 1, 0], [0, -2.2, -1]])
    return R3.dot(x)
f3(f2(f1(A)))

matrix([[ 0. ,  0. ,  3. ],
        [ 0. , -2. , -0.5],
        [ 1. ,  8.4, -2.4]])

____________________
Собственные векторы линейного оператора
_____________________
Характеристический полином матрицы

In [37]:
# Если из матрицы A вычесть единичную матрицу E, умноженную на некоторую
# переменную Л, то получим матрицу, которая называется характеристической
# матрицей матрицы A:

# Определитель такой матрицы будет полиномом n-ой степени от Л и может рассматриваться как функция:
A = np.matrix("1 4 1; 0 2 2 ; 0 0 3")
print(A)
w, v = np.linalg.eig(A)
w

[[1 4 1]
 [0 2 2]
 [0 0 3]]


array([1., 2., 3.])

In [40]:
A = np.array([[1,4,1],[0,2,2],[0,0,3]])
print(A)
w, v = np.linalg.eig(A)
w

[[1 4 1]
 [0 2 2]
 [0 0 3]]


array([1., 2., 3.])

Собственные векторы и собственные значения линейного оператора

In [41]:
# В самом начале раздела 4.4 мы ввели понятие линейного оператора. Если линейный
# оператор переводит некоторый вектор x в вектор Лx, то такой вектор называется
# собственным вектором оператора f: f(x)=Лx
# При этом Лx называется собственным значением линейного оператора f.

# Полученный вектор является коллинеарным, то есть он равен исходному вектору, умноженному на какое-то число.

# Собственными значениями линейного оператора могут быть только корни
# характеристического уравнения матрицы этого линейного оператора. При этом из
# корней следует выбирать только те, которые принадлежат полю над которым
# построено линейное пространство. То есть, если у нас элементы вектора - это
# действительные числа, то из всех собственных значений нужно выбрать те, которые
# являются действительными числами, а если есть комплексные, что возможно при
# решении уравнения, то их следует отбросить.



______________________________
Глава 5. Разложения матриц
______________________________
LU-разложение матрицы

In [5]:
# LU -разложение используется для представления матрицы в виде произведения двух
# матриц: L - нижней треугольной матрицы и U - верхней треугольной матрицы: A = LU

# У матрицы L все элементы главной диагонали равны единице. Матрицу A можно
# представить в виде LU -разложения, если все главные диагональные миноры не
# вырождены (отличны от нуля).

# Разложение такого типа используется для:
# • решения систем линейных уравнений;
# • вычисления обратной матрицы;
# • вычисления определителя.

A = np.array([[4, 1, 3], [8, 1, 8], [-12, -4, -6]])
A 

array([[  4,   1,   3],
       [  8,   1,   8],
       [-12,  -4,  -6]])

In [7]:
R1=np.array([[1, 0, 0],[2, -1, 0],[3, 0, 1]])
R2=np.array([[1, 0, 0],[0, 1, 0],[0, 1, 1]])
U = R2.dot(R1.dot(A))
U

array([[ 4,  1,  3],
       [ 0,  1, -2],
       [ 0,  0,  1]])

In [8]:
T = R2.dot(R1)
T 

array([[ 1,  0,  0],
       [ 2, -1,  0],
       [ 5, -1,  1]])

In [9]:
L = np.linalg.inv(T)
L

array([[ 1.,  0.,  0.],
       [ 2., -1., -0.],
       [-3., -1.,  1.]])

In [10]:
L.dot(U)

array([[  4.,   1.,   3.],
       [  8.,   1.,   8.],
       [-12.,  -4.,  -6.]])

In [12]:
# LU -разложение можно выполнить, используя специальную функцию из библиотеки
# scipy, эту библиотеку необходимо предварительно установить и импортировать. За
# данный тип разложения отвечает scipy.linalg.lu. В результате будут получены
# матрицы P,L и U. Смысл матриц L и U остается тот же, матрица P - это простая
# перестановочная матрица.
import scipy.linalg as la
P, L, U = la.lu(A)
print(P)
print(L)
print(U)
print(A)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
[[ 1.          0.          0.        ]
 [-0.66666667  1.          0.        ]
 [-0.33333333  0.2         1.        ]]
[[-12.          -4.          -6.        ]
 [  0.          -1.66666667   4.        ]
 [  0.           0.           0.2       ]]
[[  4   1   3]
 [  8   1   8]
 [-12  -4  -6]]


In [13]:
P.dot(L.dot(U))

array([[  4.,   1.,   3.],
       [  8.,   1.,   8.],
       [-12.,  -4.,  -6.]])

_________________________
QR-разложение матрицы

In [14]:
# По определению QR разложение матрицы является представлением матрицы в виде
# произведения ортогональной матрицы Q и верхней треугольной матрицы R. С
# понятием верней треугольной матрицы мы уже встречались ранее. Ортогональная
# матрица - новое для нас понятие, разберем его более подробно. Ортогональная
# матрица - это такая матрица, у которой ее транспонированная матрица равна
# обратной матрице, сумма квадратов всех элементов строки или столбца равна
# единице, а попарное произведение элементов двух строк или столбцов равно нулю.

# Существует несколько способов получения QR разложения матрицы. Рассмотрим
# один из них, суть которого заключается в ортогонализации и нормировании столбцов
# исходной матрицы.

# Рассмотрим быстрый способ получения QR-разложения матрицы, для этого
# воспользуемся функцией np.linalg.qr() из библиотеки Numpy. В качестве аргумента в
# эту функцию передается исходная матрица, результатом ее работы являются две матрицы и :
A = np.matrix("2 1 3; 0 1 4; 1 3 4")
A


matrix([[2, 1, 3],
        [0, 1, 4],
        [1, 3, 4]])

In [17]:
q, r = np.linalg.qr(A)
q

matrix([[-0.89442719,  0.40824829, -0.18257419],
        [-0.        , -0.40824829, -0.91287093],
        [-0.4472136 , -0.81649658,  0.36514837]])

In [16]:
r

matrix([[-2.23606798, -2.23606798, -4.47213595],
        [ 0.        , -2.44948974, -3.67423461],
        [ 0.        ,  0.        , -2.73861279]])

In [18]:
q.dot(r)

matrix([[2., 1., 3.],
        [0., 1., 4.],
        [1., 3., 4.]])

______________________
Сингулярное разложение матрицы

In [20]:
A = np.matrix("1 0 1; 0 1 0; 1 0 1")
A

matrix([[1, 0, 1],
        [0, 1, 0],
        [1, 0, 1]])

In [24]:
u, s, v = np.linalg.svd(A)
u

matrix([[-7.07106781e-01, -1.57009246e-16, -7.07106781e-01],
        [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
        [-7.07106781e-01,  1.57009246e-16,  7.07106781e-01]])

In [26]:
s

array([2.00000000e+00, 1.00000000e+00, 3.35470445e-17])

In [25]:
v

matrix([[-0.70710678,  0.        , -0.70710678],
        [ 0.        ,  1.        ,  0.        ],
        [ 0.70710678,  0.        , -0.70710678]])

_________________________
Комплексные числа
__________________________
Задание комплексных чисел

Алгебраическая форма задания комплексного числа


In [27]:
# В алгебраической форме комплексное число записывается так: z = a+ib
# где a - действительная часть;
# b - мнимая часть.
# i называют мнимой единицей, квадрат которой равен единице i**2 = -1 .

______________________
Геометрическая интерпретация комплексного числа

In [28]:
# Геометрически комплексное число z = a +ib можно рассматривать как точку на
# двумерной плоскости, на которой a и b являются координатами. На комплексной
# плоскости определяют действительную ось, она обозначается Re, и мнимую ось - обозначается Im.

___________________
Модуль и аргумент комплексного числа

In [29]:
# Помимо действительной и мнимой части комплексное число может быть определено
# с помощью модуля и аргумента. Модуль комплексного числа - это длинна вектора, а
# аргумент - угол между вектором и действительной осью.

_________________
Тригонометрическая форма задания комплексного числа

_____________________
Задание комплексного числа в Python

In [30]:
# Комплексные числа могут быть заданы парой (a,b), что сразу наталкивает на мысль
# использования кортежей Python для работы с ними:
z = (1,2)
print(z)

(1, 2)


In [31]:
# Но в этом случае придется самостоятельно написать функции для выполнения
# арифметических операций с комплексными числами. Мы этого делать не будем,
# вместо этого воспользуемся типом complex:
z = complex(1,2)
print(z)

(1+2j)


In [32]:
z1 = complex('1+3j')
print(z1)

(1+3j)


In [34]:
# Как вы можете видеть, при распечатке такого числа оно представляется в знакомой
# нам алгебраической форме. Действительная и мнимая части числа могут быть
# получены с помощью специальных атрибутов:
z.real

1.0

In [35]:
z.imag

2.0

In [36]:
# В типе complex нет методов для вычисления модуля и аргумента, для этого можно
# воспользоваться функциями из модуля cmath. Импортируем этот модуль:
import cmath

In [37]:
# Модуль r и аргумент a созданного выше числа z определяется так:
r = cmath.polar(z)[0]
print(r)
f = cmath.phase(z)
print(f)

2.23606797749979
1.1071487177940904


_________________
Комплексно сопряженное число

In [38]:
# Числом, сопряженным с комплексным z =a+ib называют z=a-ib .
z = complex(1, 2)
print(z)
c_z = z.conjugate()
print(c_z)

(1+2j)
(1-2j)


___________________________
Операции над комплексными числами
_____________________________
Сложение комплексных чисел

In [39]:
# При сложении комплексных чисел действительные и мнимые части складываются по отдельности:
z = complex('1+2j')
x = complex('3+4j')
z + x

(4+6j)

__________________
Вычитание комплексных чисел

In [40]:
# При получении разности комплексных чисел вычитание действительных и мнимых частей производится по отдельности
z = complex('5+3j')
x = complex('2+4j')
z - x

(3-1j)

__________________________
Умножение комплексных чисел

In [41]:
# Рассмотрим умножение комплексных чисел. Оно выполняется по алгебраическим правилам умножения сумм в скобках
z = complex('5+3j')
x = complex('2+4j')
z * x

(-2+26j)

_________________________
Деление комплексных чисел

In [42]:
# Для вычисления частного от деления двух комплексных чисел используется вот такая формула:
z = complex('5+3j')
x = complex('2+4j')
z / x

(1.1-0.7j)

_______________________
Возведение в степень комплексного числа

In [43]:
# При возведении в степень комплексного числа удобно работать с
# тригонометрической формой записи числа, это позволит использовать формулу Муавра:
z = complex('1+2j')
z**2

(-3+4j)

_______________________________
Извлечение корня из комплексного числа

In [48]:
# При извлечении корня из комплексного числа, также удобно представлять его в
# тригонометрической форме. Корень n-ой степени из комплексного числа будет равен
# n-му количеству корней, вычисляемых по формуле:
import math
import cmath
z = complex('3+4j')
r = abs(z)
ph = cmath.phase(z)
x1 = complex((r**0.5)*math.cos(ph/2), (r**0.5)*math.sin(ph/2))
print(x1)
x2 = complex((r**0.5)*math.cos((ph+2*cmath.pi)/2),(r**0.5)*math.sin((ph+2*cmath.pi)/2))
print(x2)

(2+1j)
(-2.0000000000000004-0.9999999999999999j)
