In [2]:
import numpy as np

In [3]:
#В общем виде вектор столбец можно задать следующим образом:.
v = np.array([[1],[2]])
print(v)

[[1]
 [2]]


In [4]:
#В Numpy можно создать квадратную матрицу с помощью метода array():
m_sqr_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m_sqr_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# В Numpy есть еще одни способ создания матриц - это построение объекта типа
# matrix с помощью одноименного метода. Задать матрицу можно в виде списка:
m_sqr_mx = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m_sqr_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
# Также доступен стиль Matlab, когда между элементами ставятся пробелы, а строки
# разделяются точкой с запятой, при этом такое описание должно быть передано в
# виде строки:
m_sqr_mx = np.matrix('1 2 3; 4 5 6; 7 8 9')
print(m_sqr_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


______________________
Диагональная матрица

In [7]:
# Диагональная матрица
#Диагональную матрицу можно построить вручную, задав только значения элементам на главной диагонали:
m_diag = [[1, 0, 0], [0, 5, 0], [0, 0, 9]]
m_diag = np.matrix(m_diag)
print(m_diag)

[[1 0 0]
 [0 5 0]
 [0 0 9]]


In [8]:
m_sqr_mx = np.matrix('1 2 3; 4 5 6; 7 8 9')

In [9]:
# Извлечем ее главную диагональ:
diag = np.diag(m_sqr_mx)
print(diag)

[1 5 9]


In [10]:
m_diag_np = np.diag(np.diag(m_sqr_mx))
print(m_diag_np)

[[1 0 0]
 [0 5 0]
 [0 0 9]]


__________________
Единичная матрица

In [11]:
# Создадим единичную матрицу на базе списка, который передадим в качестве
# аргумента функции matrix():
m_e = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
m_e_np = np.matrix(m_e)
print(m_e_np)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [13]:
#Такой способ не очень удобен, к счастью для нас, для построения такого типа
#матриц в библиотеке Numpy есть специальная функция — eye():
m_eye = np.eye(3)
print(m_eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


_______________
Нулевая матрица

In [14]:
m_zeros = np.zeros((3, 3))
print(m_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


_______________________
Задание матрицы в общем виде

In [15]:
# Если у вас уже есть данные о содержимом матрицы, то создать ее можно, используя
# списки Python или функцию matrix() из библиотеки Numpy:
m_mx = np.matrix('1 2 3; 4 5 6')
print(m_mx)

[[1 2 3]
 [4 5 6]]


In [16]:
# Если же вы хотите создать матрицу заданного размера
# с произвольным
# содержимым, чтобы потом ее заполнить, проще всего для того использовать
# функцию zeros(), которая создаст матрицу заданного размера, заполненную нулями:

m_var = np.zeros((2,5))
print(m_var)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


______________________
Транспонирование матрицы

In [ ]:
# Транспонирование матрицы - это процесс замены строк матрицы на ее столбцы, а
# столбцов, соответственно, на строки. Полученная в результате матрица называется
# транспонированной. Символ операции транспонирования - буква T


In [17]:
A = np.matrix('1 2 3; 4 5 6')
print(A)

[[1 2 3]
 [4 5 6]]


In [18]:
# Транспонируем матрицу с помощью метода transpose():
A_t = A.transpose()
print(A_t)

[[1 4]
 [2 5]
 [3 6]]


In [19]:
# Существует сокращенный вариант получения транспонированной матрицы, он
# удобен для практического использования:
print(A.T)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# Свойство 1. Дважды транспонированная матрица равна исходной матрице:


In [20]:
A = np.matrix('1 2 3; 4 5 6')
print(A)
R = (A.T).T
print(R)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [ ]:
# Свойство 2. Транспонированная сумма матриц равна сумме транспонированных матриц:

In [21]:
A = np.matrix('1 2 3; 4 5 6')
B = np.matrix('7 8 9; 0 7 5')
L = (A + B).T
R = A.T + B.T
print(L)
print(R)

[[ 8  4]
 [10 12]
 [12 11]]
[[ 8  4]
 [10 12]
 [12 11]]


In [22]:
# Свойство 3. Транспонированное произведение матриц равно произведению
# транспонированных матриц, расставленных в обратном порядке:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
L = (A.dot(B)).T
R = (B.T).dot(A.T)
print(L)
print(R)

[[19 43]
 [22 50]]
[[19 43]
 [22 50]]


In [23]:
# Свойство 4. Транспонированное произведение матрицы на число равно произведению этого числа на транспонированную матрицу:
A = np.matrix('1 2 3; 4 5 6')
k = 3
L = (k * A).T
R = k * (A.T)
print(L)
print(R)

[[ 3 12]
 [ 6 15]
 [ 9 18]]
[[ 3 12]
 [ 6 15]
 [ 9 18]]


In [25]:
# Свойство 5. Определители исходной и транспонированной матрицы совпадают:
A = np.matrix('1 2; 3 4')
A_det = np.linalg.det(A)
A_T_det = np.linalg.det(A.T)
print(format(A_det, '.9g'))
print(format(A_T_det, '.9g'))

-2
-2


_________________
Действия над матрицами
_________________
Умножение на число

In [26]:
A = np.matrix('1 2 3; 4 5 6')
C = 3 * A
print(C)

[[ 3  6  9]
 [12 15 18]]


In [27]:
# Свойство 1. Произведение единицы и любой заданной матрицы равно заданной матрице: 
A = np.matrix('1 2; 3 4')
L = 1 * A
R = A
print(L)
print(R)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [28]:
# Свойство 2. Произведение нуля и любой матрицы равно нулевой матрице,
# размерность которой равна исходной матрицы:
A = np.matrix('1 2; 3 4')
Z = np.matrix('0 0; 0 0')
L = 0 * A
R = Z
print(L)
print(R)

[[0 0]
 [0 0]]
[[0 0]
 [0 0]]


In [29]:
# Свойство 3. Произведение матрицы на сумму чисел равно сумме произведений
# матрицы на каждое из этих чисел:
A = np.matrix('1 2; 3 4')
p = 2
q = 3
L = (p + q) * A
R = p * A + q * A
print(L)
print(R)

[[ 5 10]
 [15 20]]
[[ 5 10]
 [15 20]]


In [31]:
# Свойство 4. Произведение матрицы на произведение двух чисел равно произведению второго числа и заданной матрицы, умноженному на первое число:
A = np.matrix('1 2; 3 4')
p = 2 
q = 3
L = (p * q) * A
R = p * (q * A)
print(L)
print(R)

[[ 6 12]
 [18 24]]
[[ 6 12]
 [18 24]]


In [34]:
# Свойство 5. Произведение суммы матриц на число равно сумме произведений этих
# матриц на заданное число:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
k = 3
L = k * (A + B)
R = k * A + k * B
print(L)
print(R)

[[18 24]
 [30 36]]
[[18 24]
 [30 36]]


________________________
Сложение

In [35]:
# Складывать можно только матрицы одинаковой размерности — то есть матрицы, у
# которых совпадает количество столбцов и строк.
A = np.matrix('1 6 3; 8 2 7')
B = np.matrix('8 1 5; 6 9 12')
C = A + B
print(C)

[[ 9  7  8]
 [14 11 19]]


In [36]:
# Свойство 1. Коммутативность сложения. От перестановки матриц их сумма не изменяется:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
L = A + B
R = B + A
print(L)
print(R)

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [37]:
# Свойство 2. Ассоциативность сложения. Результат сложения трех и более матриц
# не зависит от порядка, в котором эта операция будет выполняться:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
C = np.matrix('1 7; 9 3')
L = A + (B + C)
R = (A + B) + C
print(L)
print(R)

[[ 7 15]
 [19 15]]
[[ 7 15]
 [19 15]]


In [38]:
# Свойство 3. Для любой матрицы A существует противоположная ей (-A) такая, что их сумма является нулевой матрицей Z
A = np.matrix('1 2; 3 4')
Z = np.matrix('0 0; 0 0')
L = A + (-1)*A
print(L)
print(Z)

[[0 0]
 [0 0]]
[[0 0]
 [0 0]]


_________________________
Умножение матриц

In [39]:
# Умножение матриц это уже более сложная операция,по сравнению с
# рассмотренными выше. Умножать можно только матрицы, отвечающие следующему
# требованию: количество столбцов первой матрицы должно быть равно числу
# строк второй матрицы.
# Решим задачу умножения матриц на языке Python. Для этого будем использовать
# функцию dot() из библиотеки Numpy:
A = np.matrix('1 2 3; 4 5 6')
B = np.matrix('7 8; 9 1; 2 3')
C = A.dot(B)
print(C)

[[31 19]
 [85 55]]


In [41]:
# Свойство 1. Ассоциативность умножения. Результат умножения матриц не зависит
# от порядка, в котором будет выполняться эта операция:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
C = np.matrix('2 4; 7 8')
L = A.dot(B.dot(C))
R = (A.dot(B)).dot(C)
print(L)
print(R)

[[192 252]
 [436 572]]
[[192 252]
 [436 572]]


In [42]:
# Свойство 2. Дистрибутивность умножения. Произведение матрицы на сумму
# матриц равно сумме произведений матриц:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
C = np.matrix('2 4; 7 8')
L = A.dot(B + C)
R = A.dot(B) + A.dot(C)
print(L)
print(R)

[[35 42]
 [77 94]]
[[35 42]
 [77 94]]


In [45]:
# Свойство 3. Умножение матриц в общем виде не коммутативно. Это означает, что
# для матриц не выполняется правило независимости произведения от перестановки множителей:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
L = A.dot(B)
R = B.dot(A)
print(L)
print(L)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [46]:
# Свойство 4. Произведение заданной матрицы на единичную равно исходной матрице:
A = np.matrix('1 2; 3 4')
E = np.matrix('1 0; 0 1')
L = E.dot(A)
R = A.dot(E)
print(L)
print(R)
print(A)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [47]:
# Свойство 5. Произведение заданной матрицы на нулевую матрицу равно нулевой матрице:
A = np.matrix('1 2; 3 4')
Z = np.matrix('0 0; 0 0') 
L = Z.dot(A)
R = A.dot(Z)
print(L)
print(R)
print(Z)

[[0 0]
 [0 0]]
[[0 0]
 [0 0]]
[[0 0]
 [0 0]]


______________________
Определитель матрицы

In [3]:
# Определитель матрицы размера n x n( -го порядка) является одной из ее численных характеристик. Определитель матрицы A
# обозначается как |A| или det(A) его также называют детерминантом.

# Минор элемента определителя - это определитель, полученный из данного, путем вычеркивания всех элементов строки и
# столбца, на пересечении которых стоит данный элемент.

# Введем еще одно понятие - алгебраическое дополнение элемента определителя - это минор этого элемента, взятый со знаком плюс или минус:
# В общем виде вычислить определитель матрицы можно через разложение
# определителя по элементам строки или столбца. Суть в том, что определитель равен
# сумме произведений элементов любой строки или столбца на их алгебраические
# дополнения.

# На Python определитель посчитать очень просто. Создадим матрицу размера 3x3 из приведенного выше численного примера:

A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]


In [4]:
# Для вычисления определителя этой матрицы воспользуемся функцией det() из пакета linalg.
np.linalg.det(A)

-14.000000000000009

In [5]:
# Свойство 1. Определитель матрицы остается неизменным при ее транспонировании:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)
print(A.T)
det_A = round(np.linalg.det(A), 3)
det_A_t = round(np.linalg.det(A.T), 3)
print(det_A)
print(det_A_t)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]
[[-4 10  8]
 [-1  4  3]
 [ 2 -1  1]]
-14.0
-14.0


In [6]:
# Свойство 2. Если у матрицы есть строка или столбец, состоящие из нулей, то определитель такой матрицы равен нулю:
A = np.matrix('-4 -1 2; 0 0 0; 8 3 1')
print(A)
np.linalg.det(A)

[[-4 -1  2]
 [ 0  0  0]
 [ 8  3  1]]


0.0

In [14]:
# Свойство 3. При перестановке строк матрицы знак ее определителя меняется на противоположный:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)
B = np.matrix('10 4 -1; -4 -1 2; 8 3 1')
print(B)
round(np.linalg.det(A), 3)
round(np.linalg.det(B), 3)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]
[[10  4 -1]
 [-4 -1  2]
 [ 8  3  1]]


14.0

In [23]:
round(np.linalg.det(B), 3)

-14.0

In [15]:
# Свойство 4. Если у матрицы есть две одинаковые строки, то ее определитель равен нулю:
A = np.matrix('-4 -1 2; -4 -1 2; 8 3 1')
print(A)
np.linalg.det(A)

[[-4 -1  2]
 [-4 -1  2]
 [ 8  3  1]]


0.0

In [16]:
# Свойство 5. Если все элементы строки или столбца матрицы умножить на какое-то число, то и определитель будет умножен на это число:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)
k = 2
B = A.copy()
B[2, :] = k * B[2, :]
print(B)
det_A = round(np.linalg.det(A), 3)
det_B = round(np.linalg.det(B), 3)
det_A * k
det_B

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]
[[-4 -1  2]
 [10  4 -1]
 [16  6  2]]


-28.0

In [21]:
# Свойство 6. Если все элементы строки или столбца можно представить как сумму 
# двух слагаемых, то определитель такой матрицы равен сумме определителей двух
# соответствующих матриц:
A = np.matrix('-4 -1 2; -4 -1 2; 8 3 1')
B = np.matrix('-4 -1 2; 8 3 2; 8 3 1')
C = A.copy()
C[1, :] += B[1, :]
print(C)
print(A)
print(B)
round(np.linalg.det(C), 3)
round(np.linalg.det(A), 3) + round(np.linalg.det(B), 3)

[[-4 -1  2]
 [ 4  2  4]
 [ 8  3  1]]
[[-4 -1  2]
 [-4 -1  2]
 [ 8  3  1]]
[[-4 -1  2]
 [ 8  3  2]
 [ 8  3  1]]


4.0

In [22]:
# Свойство 7. Если к элементам одной строки прибавить элементы другой строки
# умноженные на одно и тоже число, то определитель матрицы не изменится:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
k = 2
B = A.copy()
B[1, :] = B[1, :] + k * B[0, :]
print(A)
print(B)
round(np.linalg.det(A), 3)
round(np.linalg.det(B), 3)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]
[[-4 -1  2]
 [ 2  2  3]
 [ 8  3  1]]


-14.0

In [27]:
# Свойство 8. Если строка или столбец матрицы является линейной комбинацией
# других строк (столбцов), то определитель такой матрицы равен нулю:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)
k = 2
A[1, :] = A[0, :] + k * A[2, :]
round(np.linalg.det(A), 3)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]


0.0

In [28]:
# Свойство 9. Если матрица содержит пропорциональные строки, то ее определитель равен нулю:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)
k = 2
A[1, :] = k * A[0, :]
print(A)
round(np.linalg.det(A), 3)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]
[[-4 -1  2]
 [-8 -2  4]
 [ 8  3  1]]


0.0

_________________________
Обратная матрица

In [30]:
# Введем понятие союзной матрицы. Союзная матрица A* строится на базе
# исходной A путем замены всех элементов матрицы A на их алгебраические
# дополнения.

# Решим задачу определения обратной матрицы на Python. Для получения обратной
# матрицы будем использовать функцию inv():
A = np.matrix('1 -3; 2 5')
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.45454545  0.27272727]
 [-0.18181818  0.09090909]]


In [31]:
# Свойство 1. Обратная матрица обратной матрицы есть исходная матрица:
A = np.matrix('1. -3.; 2. 5.')
A_inv = np.linalg.inv(A)
A_inv_inv = np.linalg.inv(A_inv)
print(A)
print(A_inv_inv)

[[ 1. -3.]
 [ 2.  5.]]
[[ 1. -3.]
 [ 2.  5.]]
