In [1]:
import numpy as np

In [2]:
v_hor_np = np.array([1, 2])
print(v_hor_np)

[1 2]


In [3]:
# создаем нулевую вектор строку сосотоящую из 5 элементов
v_hor_zeros_v1 = np.zeros((5,))
print(v_hor_zeros_v1)

[0. 0. 0. 0. 0.]


In [4]:
# В случае, если требуется построить вектор-строку так, чтобы он сам являлся 
# элементом массива, это может понадобиться если вектор, в последующем, нужно
# будет транспонировать (см. раздел “1.3 Транспонирование матрицы”), то данная задача решается так:
v_hor_zeros_v2 = np.zeros((1, 5))
print(v_hor_zeros_v2)

[[0. 0. 0. 0. 0.]]


In [5]:
# В общем виде вектор столбец можно задать следующим образом:
v_vert_np = np.array([[1], [2]])
print(v_vert_np)

[[1]
 [2]]


In [6]:
# Построим нулевой вектор-столбец:
v_vert_zeros = np.zeros((5, 1))
print(v_vert_zeros)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [7]:
# Единичный вектор-столбец можно создать с помощью функции ones():
v_vert_ones = np.ones((5, 1))
print(v_vert_ones)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


-Квадратная матрица

In [8]:
# В Numpy можно создать квадратную матрицу с помощью метода array():
m_sqr_arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m_sqr_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
# еще один способ построения матрицы 
m_sqr = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
m_sqr_arr = np.array(m_sqr)
print(m_sqr_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
# В Numpy есть еще одни способ создания матриц - это построение объекта типа 
# matrix с помощью одноименного метода. Задать матрицу можно в виде списка:
m_sqr_mx = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m_sqr_mx)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
# Также доступен стиль Matlab, когда между элементами ставятся пробелы, а строки
# разделяются точкой с запятой, при этом такое описание должно быть передано в виде строки:
m_sqr_mx = np.matrix('1 2 3; 4 5 6; 7 8 9')
print(m_sqr_mx)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


-Диагональная матрица

In [12]:
# Диагональную матрицу можно построить вручную, задав только значения элементам на главной диагонали: 
m_diag = [[1, 0, 0], [0, 5, 0], [0, 0, 9]]
m_diag = np.matrix(m_diag)
print(m_diag)

[[1 0 0]
 [0 5 0]
 [0 0 9]]


In [13]:
# Создадим матрицу размера 3x3:
m_sqr_mx = np.matrix('1 2 3; 4 5 6; 7 8 9')
# Извлечем ее главную диагональ:
diag = np.diag(m_sqr_mx)
print(diag)

[1 5 9]


In [14]:
# Построим диагональную матрицу на базе полученной диагонали:
m_diag_np = np.diag(np.diag(m_sqr_mx))
print(m_diag_np)

[[1 0 0]
 [0 5 0]
 [0 0 9]]


-Единичная матрица

In [15]:
# Создадим единичную матрицу на базе списка, который передадим в качестве аргумента функции matrix():
m_e = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
m_e_np = np.matrix(m_e)
print(m_e_np)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [18]:
# библиотеке Numpy есть специальная функция — eye() для постраения единичных матриц
m_eye = np.eye(3)
print(m_eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
# В качестве аргумента функции передается размерность матрицы, в нашем примере -
# это матрица 3x3. Тот же результат можно получить с помощью функции identity():
m_idnt = np.identity(5)
print(m_idnt)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


-Нулевая матрица

In [25]:
# Numpy, то в составе этой библиотеки есть функция zeros(), которая создает нужную нам матрицу:
m_zeros = np.zeros((6,6))
print(m_zeros)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


-Транспонирование матрицы

In [29]:
A = np.matrix('1 2 3; 4 5 6; 4 5 6')
print(A)

[[1 2 3]
 [4 5 6]
 [4 5 6]]


In [27]:
# Транспонируем матрицу с помощью метода transpose():
A_t = np.transpose(A)
print(A_t)

[[1 4]
 [2 5]
 [3 6]]


In [30]:
# Существует сокращенный вариант получения транспонированной матрицы, он удобен для практического использования:
print(A.T)

[[1 4 4]
 [2 5 5]
 [3 6 6]]


Свойства траспонирования

In [33]:
# свойство 1
A = np.matrix('1 2 3; 4 5 6')
print(A)
R = (A.T).T
print(R)


[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [34]:
# Свойство 2. Транспонированная сумма матриц равна сумме транспонированных матриц:
A = np.matrix('1 2 3; 4 5 6')
B = np.matrix('7 8 9; 0 7 5')
L = (A + B).T
R = A.T + B.T
print(L)
print(R)

[[ 8  4]
 [10 12]
 [12 11]]
[[ 8  4]
 [10 12]
 [12 11]]


# Свойство 3. Транспонированное произведение матриц равно произведению транспонированных матриц, расставленных в обратном порядке:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
L = (A.dot(B)).T
R = (B.T).dot(A.T)
print(L)
print(R)

In [37]:
# Свойство 4. Транспонированное произведение матрицы на число равно произведению этого числа на транспонированную матрицу:
A = np.matrix('1 2 3; 4 5 6; 4 5 6')
k = 3
L = (k * A).T
R = k * (A.T)
print(L)
print(R)

[[ 3 12 12]
 [ 6 15 15]
 [ 9 18 18]]
[[ 3 12 12]
 [ 6 15 15]
 [ 9 18 18]]


In [39]:
# Свойство 5. Определители исходной и транспонированной матрицы совпадают:
A = np.matrix('1 2; 3 4')
A_det = np.linalg.det(A)
A_T_det = np.linalg.det(A.T)
print(format(A_det, '.9g'))
print(format(A_T_det, '.9g'))

-2
-2


-Действия над матрицами

1.4.1 Умножение на число

In [42]:
# При умножении матрицы на число, все элементы матрицы умножаются на это число:
A = np.matrix('1 2 3; 4 5 6')
C = 3 * A
print(C)

[[ 3  6  9]
 [12 15 18]]


In [43]:
# Свойство 1. Произведение единицы и любой заданной матрицы равно заданной матрице:
a = np.matrix('1 2 3; 4 5 6')
l = 1 * a
r = a
print(l)
print(r)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [45]:
# Свойство 2. Произведение нуля и любой матрицы равно нулевой матрице, размерность которой равна исходной матрицы:
a = np.matrix('1 2 3; 4 5 6')
z = np.matrix('0 0 0; 0 0 0')
l = 0 * a
r = z
print(l)
print(r)

[[0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]]


In [46]:
# Свойство 3. Произведение матрицы на сумму чисел равно сумме произведений матрицы на каждое из этих чисел:
a = np.matrix('1 2 3; 4 5 6')
p = 2
q = 3
l = (p+q)*a
r = p * a + q * a
print(l)
print(r)

[[ 5 10 15]
 [20 25 30]]
[[ 5 10 15]
 [20 25 30]]


In [48]:
a = np.matrix('1 2 3; 4 5 6')
p = 2
q = 3
l = (p*q)*a
r = p*(q*a)
print(l)
print(r)

[[ 6 12 18]
 [24 30 36]]
[[ 6 12 18]
 [24 30 36]]


In [49]:
a = np.matrix('1 2; 3 4')
b = np.matrix('5 6; 7 8')
k = 3 
l = k * (a+b)
r = k * a + k * b
print(l)
print(r)

[[18 24]
 [30 36]]
[[18 24]
 [30 36]]


-Сложение матриц